services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  app:
    build: .
    container_name: rate-limiter
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - .:/app
    command: ["go", "run", "main.go"]

volumes:
  redis-data:
